spring:
  application:
    name: demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydb?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 942699
    hikari:
      max-lifetime: 12000
  servlet:
    multipart:
      max-file-size: 100MB        #文件大小限制
      max-request-size: 100MB

server:
  port: 8090

mybatis:
  mapper-locations: classpath:mapper/*.xml     #扫描resource中mapper下的所有xml文件
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

files:
  upload:
    path: E:/Vueprog/newvue/src/assets/file/        #文件上传位置

mqtt:
  broker-url: tcp://127.0.0.1:1883
  client-id: emq-client
  username: user
  password: 123456
